//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplyTable
    {
        public int JobApplyID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime JobAppliedDateTime { get; set; }
        public int JobApplyStausID { get; set; }
        public System.DateTime JobApplyStatusUpdateDate { get; set; }
        public string JobApplyStatusUpdateReason { get; set; }
    
        public virtual EmployeesTable EmployeesTable { get; set; }
        public virtual JobApplyStatusTable JobApplyStatusTable { get; set; }
    }
}
