//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirementTable
    {
        public int JobRequirementID { get; set; }
        public string JobRequirementTitle { get; set; }
        public int PostJobID { get; set; }
    
        public virtual JobRequirementDetailTable JobRequirementDetailTable { get; set; }
        public virtual PostJobTable PostJobTable { get; set; }
    }
}
