//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobTable()
        {
            this.PostJobTables = new HashSet<PostJobTable>();
        }
    
        public int JobID { get; set; }
        public int JobCategoryID { get; set; }
        public string JobTitle { get; set; }
        public string JobRequirements { get; set; }
        public string JobDetails { get; set; }
    
        public virtual JobCategoryTable JobCategoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostJobTable> PostJobTables { get; set; }
    }
}
